### ISSUE TITLE
White flash when opened

### ISSUE THREAD

**Issue by Philipp-Codes** [kholmogorov27/chevron#10]
Whenever I open a Chevron tab (Startpage/New-Tab-Page/Home-Page/Reload) the entire page is white for a split second.
This is not ideal when using darkmode.
Is there a way to avoid this? If not I would appreciate if you could look into implementing a fix.

Thank you for creating such an amazing startpage.

**Comment by kholmogorov27** [comment]
Currently it's not possible to avoid it, but I'll make a fix soon

**Comment by kholmogorov27** [comment]
> Thank you for creating such an amazing startpage

I'm glad you like it ;)
