### ISSUE TITLE
Unable to Build (Syntax Error involving reserved word 'Await')

### ISSUE THREAD

**Issue by sunkencity999** [kholmogorov27/chevron#11]
When attempting to build, the following error is encountered: 

> chevron@2.1.0 build
> vite build

file:///home/sunkencity999/chevron-2.1.0/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by kholmogorov27** [comment]
It seems to be a known issue of vite
https://github.com/vitejs/vite/issues/9582

You need to update your Node.js version

**Comment by sunkencity999** [comment]
That resolved the issue
