### ISSUE TITLE
Hosted method not working

### ISSUE THREAD

**Issue by Sohail-XD** [kholmogorov27/chevron#13]
It might be my mistake but when I'm running this command `npm run register_linux` it gives he output like

 >chevron@2.2.0 register_linux
 >node backend/register.cjs linux

>Using default mode: systemd
>Unregistering the service'

No matter how many times I repeat it, it keeps showing unregistering. Also localhost:8000 is unable to connect. 

Any solution?

**Comment by kholmogorov27** [comment]
the bug is fixed in the 3c58ee1 commit
