### ISSUE TITLE
super wierd scrolling system

### ISSUE THREAD

**Issue by MiftikCZ** [kholmogorov27/chevron#2]
![Snímek obrazovky_2023-03-04_15-17-06](https://user-images.githubusercontent.com/89579269/222907516-12003bda-89a9-45f5-a466-54b388c22a5f.png)

## the issues
- cant scroll with mouse in the settings tab (only scrolling by tab key works)
- the main page is leaving the view after scrolling in settings tab (the issue is in the photo)
- completly broken scrolling in mobile browsers (firefox) - just after opening the page you can scroll as far as you want away from the main view

## info
- browser: firefox
- os: Arch linux with 6.2.1-arch1-1 kernel

## how to fix
- first of all, make the `body` `overflow-y = hidden` and for the settings tab make `overflow-y = auto`
- add some support for mobile browsers

**Comment by kholmogorov27** [comment]
I've fixed the issues including the scrolling issue in mobile browsers.
However fixing mobile compatibility bugs has low importance because mobile device support is not conceptually implied.
