### ISSUE TITLE
Animation Issue

### ISSUE THREAD

**Issue by itz-rj-here** [kholmogorov27/chevron#20]

**Comment by itz-rj-here** [comment]
anyways, the animation doesn't work either....

**Comment by Shywizz** [comment]
Could you detail your issue ? Personally i have had no problem when hosting myself.

**Comment by itz-rj-here** [comment]
Uhh I have fixed the hosting issue 
it wasn't working cause it wasn't able to locate a file

and now everything is working fine
except the animation doesn't work
when i do shift and open a site, the animation doesn't shows up
it shows like the site icon comes at the middle and opens the site
