### ISSUE TITLE
Support for Qwant ?

### ISSUE THREAD

**Issue by oyamabs** [kholmogorov27/chevron#3]
Hello,
Great project ! I wonder if there will be a qwant support as a search engine, I tried modifying the config.js file but it doesn't show for some reason (maybe I f'd up my file).
Can you add it ?

(I would love to fork and PR this small change, but I suck with JS and React)

**Comment by kholmogorov27** [comment]
Hey! 
I added Qwant and some other search engines. You can change search engine in `Settings` → `Search engine`.
You can also add your own search engine in `/config.js` → `engines` (you can find the template [here](https://github.com/kholmogorov27/chevron#configjs)), it must appear in the setting list after you add it.
