### ISSUE TITLE
Unable to use chatgpt integration

### ISSUE THREAD

**Issue by Iron6271** [kholmogorov27/chevron#7]
have entered api key and enabled it but on double press it still does nothing

**Comment by kholmogorov27** [comment]
Hey! Do you have any errors or warnings in the console (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>)?

**Comment by kholmogorov27** [comment]
Currently there's no any chatGPT API error handlers, I'm going to implement it in the future

**Comment by kholmogorov27** [comment]
> Currently there's no any chatGPT API error handlers, I'm going to implement it in the future

chatGPT API error handlers added in the a7bd9fd commit
