### ISSUE TITLE
config.js changes don't work

### ISSUE THREAD

**Issue by mel-edo** [kholmogorov27/chevron#9]
Hey, I downloaded the zip file from releases and if i make any changes to the config.js file, it does nothing.
And in the zip release there isn't any public folder either like in #6

I run `http-server` in the Chevron_v2.1.0 folder and go to 127.0.0.1:8080 in my browser to see the startpage

I am on Arch linux, firefox version 110.0.1

**Comment by kholmogorov27** [comment]
Hey!

From my [comment](https://github.com/kholmogorov27/chevron/issues/6#issuecomment-1465242107) in #6 issue
> The `/public` folder is used for development. After building all the files from `/public` folder copy to the `/dist` folder. When you open Chevron in browser it uses files only from the `/dist` folder.
> 
> I recommend editing `/dist/config.js` because it doesn't require rebuilding. However you can edit `public/config.js` too but you have to rebuild to apply these changes. 
>**WARNING**: Building process overwrites `/dist/config.js`
> 
> _NOTE_: Release archives consist of files from the `/dist` folder

**Comment by mel-edo** [comment]
Looks like rebuilding after editing public/config.js works!.
I'm not sure why editing the files in /dist/config.js doesen't work.

**Comment by kholmogorov27** [comment]
you should try reloading the page without caching (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd>)

**Comment by mel-edo** [comment]
I tried `Ctrl` + `shift` + `R` after making changes in /dist/config.js and it looks like that doesen't work either
